ttizze/evame

- web/app/routes/_index/utils/translation.ts
- web/app/utils/sourceTextService.ts
- web/prisma/migrations/20240714130117_/migration.sql
- web/prisma/schema.prisma
> feat: Add number parameter to getOrCreateSourceTextId function

- web/app/components/ModeToggle.tsx
- web/app/root.tsx
This pull request simplifies the theme toggle component by removing unnecessary transition classes and enhances the layout by adding a smooth color transition effect to the body element. Additionally, it cleans up the ThemeProvider component by consolidating its props for better readability.
> Refactor theme toggle and layout transitions

- web/app/routes/$userName+/page+/$slug+/components/sourceTextAndTranslationSection/TranslationSection.tsx
- web/app/routes/$userName+/page+/$slug+/edit/utils/addNumbersToContent.ts
- web/vite.config.ts
This pull request removes the remix development tools due to performance concerns and includes some code cleanup. Unused imports and unnecessary components have been eliminated to streamline the codebase. Additionally, minor adjustments have been made to improve readability and maintainability.
> Remove remix dev tools and clean up code

- web/app/routes/$userName+/page+/$slug+/components/FloatingControls.tsx
This PR improves the button styles in the FloatingControls component by correcting the application of class names based on conditions. The changes ensure that the correct styles are applied when toggling the visibility of original text and translations.
> Fix button styles and class name application in FloatingControls component

- web/app/routes/_index/index.tsx
- web/app/routes/auth/login/route.tsx
This PR enhances the login page by adding links to the Terms of Service and Privacy Policy. Additionally, it modifies the display logic to show the Start button only when the user is not logged in. This improves user experience by providing important legal information upfront.
> Add links to Terms of Service and Privacy Policy on login page

- web/app/routes/$userName+/edit/functions/mutations.server.ts
- web/app/routes/$userName+/edit/route.tsx
- web/app/routes/$userName+/index.tsx
- web/app/routes/$userName+/page+/$slug+/components/ShareDialog.tsx
This pull request expands the data type for the user update function and fixes the username duplication check. It also improves the layout of the profile editing screen and enhances error message display. Additionally, a copy icon has been added to the ShareDialog component, allowing users to copy the URL to the clipboard, along with adjustments to the dialog's styling.
> Enhance user profile update and sharing features

- web/app/routes/$userName+/page+/$slug+/components/ContentWithTranslations.tsx
- web/app/routes/$userName+/page+/$slug+/index.tsx
This pull request enhances the layout of the translations section by introducing a flexbox design for better alignment and spacing. Additionally, it adds an edit button for user-owned translations, allowing users to easily access the edit page for their content. The changes aim to improve user experience and accessibility within the translation interface.
> Improve layout and add edit button for user-owned translations

- web/app/routes/$userName+/page+/$slug+/edit/_edit.tsx
- web/app/routes/$userName+/page+/$slug+/edit/components/EditHeader.tsx
This pull request removes unnecessary whitespace from the edit page and introduces a mode toggle in the header for improved user experience. The changes enhance the overall layout and functionality of the edit page.
> Edit page: clean up whitespace and add mode toggle feature

- web/app/routes/$userName+/page+/$slug+/components/ContentWithTranslations.tsx
- web/app/routes/$userName+/page+/$slug+/components/translateButton/TranslateButton.tsx
- web/app/routes/$userName+/page+/$slug+/index.tsx
This pull request introduces a tag display feature in the `ContentWithTranslations` component, allowing users to see associated tags more clearly. Additionally, the `TranslateButton` has been updated to improve user experience by adding a label next to the language icon, making it more intuitive. These changes aim to enhance the overall usability of the translation interface.
> Add tag display and enhance TranslateButton for improved UX

- web/app/routes/$userName+/page+/$slug+/components/ContentWithTranslations.tsx
- web/app/routes/$userName+/page+/$slug+/components/ParsedContent.tsx
- web/app/routes/$userName+/page+/$slug+/components/translateButton/TranslateButton.tsx
- web/app/routes/$userName+/page+/$slug+/edit/components/editor/EditorKeyboardMenu.tsx
This pull request refactors the `ContentWithTranslations` component to improve the layout by adjusting margins and adding a new section for displaying tags. Additionally, it modifies the `EditorKeyboardMenu` component to streamline the button structure and introduces an image upload feature, enhancing the user experience for inserting images. The changes also include the removal of unused props and code cleanup for better maintainability.
> Refactor ContentWithTranslations and EditorKeyboardMenu components

- web/app/routes/_index/index.tsx
This pull request introduces the use of the `@floating-ui/react` library in the index route. It adds floating references and styles to enhance the user interface, allowing for improved positioning of elements based on user interactions. The changes include updates to the component's props to accommodate the new floating functionality.
> Add floating UI functionality to index route

- web/app/features/translate/services/anthropic.ts
- web/app/features/translate/services/openai.ts
- web/app/routes/_index/index.tsx
This pull request cleans up the code by removing unused imports and commenting out functions related to the Anthropic and OpenAI APIs. This helps improve code readability and maintainability by eliminating unnecessary clutter. Additionally, it introduces a new prop, `floatingRefs`, in the `Index` component to enhance its functionality.
> Remove unused imports and commented-out code

- web/app/routes/$userName+/page+/$slug+/index.tsx
- web/app/routes/_index/index.tsx
- web/app/routes/resources+/translation-list-item.tsx
This pull request enhances the layout and styling of several components. It adjusts padding in the article section of the page, removes unnecessary props from the Index component, and modifies the styling of the translation list item for better visual consistency. These changes aim to improve the overall user experience and readability of the application.
> Improve layout and styling in various components

- web/app/routes/$userName+/page+/$slug+/components/ContentWithTranslations.tsx
- web/app/routes/$userName+/page+/$slug+/components/sourceTextAndTranslationSection/SourceTextAndTranslationSection.tsx
This pull request refactors the `ContentWithTranslations` and `SourceTextAndTranslationSection` components to improve code organization and readability. It simplifies the layout by removing unnecessary wrapper elements and enhances the user experience by conditionally rendering the edit button for the owner of the content. Additionally, it maintains the existing functionality while ensuring a cleaner structure for future development.
> Refactor ContentWithTranslations and SourceTextAndTranslationSection components

- web/app/components/ModeToggle.tsx
- web/app/routes/resources+/header.tsx
This pull request modifies the `ModeToggle` component to correctly toggle between light and dark themes, ensuring that the logic reflects the current theme state. Additionally, it updates the `Header` component to replace `Link` with `NavLink` for better navigation handling, incorporating pending state styling for improved user experience.
> Refactor theme toggle and update header navigation links

- web/app/features/translate/constants.ts
- web/app/features/translate/translate-user-queue.ts
- web/app/routes/$userName+/page+/$slug+/components/sourceTextAndTranslationSection/SourceTextAndTranslationSection.tsx
- web/app/routes/$userName+/page+/$slug+/components/translateButton/TranslateSettingsDialog.tsx
- web/app/routes/$userName+/page+/$slug+/edit/functions/mutations.server.ts
- web/package.json
- web/prisma/migrations/20241212094515_/migration.sql
- web/prisma/migrations/20241212094802_/migration.sql
- web/prisma/migrations/20241212095253_/migration.sql
- web/prisma/schema.prisma
- web/scripts/ranking.html
- web/scripts/syncMarkdown.ts
- web/scripts/translate.ts
This pull request introduces several database indexes to enhance query performance across various models, including `User`, `Page`, and `TranslateText`. Additionally, it updates the translation settings and improves the handling of source text mutations, ensuring more efficient processing. These changes aim to optimize the overall performance of the application and streamline translation workflows.
> Add database indexes and improve translation settings

- web/app/routes/$userName+/page+/$slug+/edit/functions/mutations.server.ts
- web/prisma/seed.ts
This pull request improves the `synchronizePageSourceTexts` function by ensuring that operations are scoped to the correct `pageId`, enhancing data integrity during updates and deletions. Additionally, it updates the user creation logic to include a default icon for the user "evame", ensuring a consistent user experience.
> Enhance source text synchronization and user creation logic

- web/app/components/BaseHeaderLayout.tsx
- web/app/routes/$userName+/page+/$slug+/edit/utils/processHtmlContent.test.ts
- web/scripts/SyncGithub.test.ts
This pull request addresses the user name display issue by updating the relevant component to use the correct property. Additionally, it introduces a new test for the HTML content processing functionality, ensuring that images are not wrapped in `<p>` tags and validating the expected output. This enhances the robustness of the HTML processing feature.
> Fix user name display and add HTML content processing test

- render.yaml
- web/app/features/translate/services/texTra.ts
This pull request updates the build command in `render.yaml` to streamline the installation process. Additionally, it introduces a new service for integrating the TexTra API, which includes functions for obtaining access tokens, performing translations, and validating API keys. This integration enhances the application's translation capabilities by leveraging TexTra's services.
> Update build command and integrate TexTra API

- next/sentry.client.config.ts
Include browser tracing integration in the Sentry setup and fix indentation for better readability.
> Add browser tracing integration to Sentry configuration

- next/src/app/[locale]/(edit-layout)/user/[handle]/page/[slug]/edit/components/header/action.ts
- next/src/app/[locale]/(edit-layout)/user/[handle]/page/[slug]/edit/components/header/index.tsx
- next/src/app/[locale]/(edit-layout)/user/[handle]/page/[slug]/edit/components/header/lib/handle-page-translation.test.ts
- next/src/app/[locale]/components/header/index.tsx
- next/src/lib/prisma.ts
Eliminate redundant imports, improve form data parsing, and add error messages for page ID. Update loading indicators for better user experience.
> Remove unnecessary imports and enhance form handling with loading indicators

- next/src/app/[locale]/_components/footer.tsx
Change the footer component to utilize internationalization links for improved localization support. Fix the import statement for the internationalization link.
> Update footer component to use internationalization links

- next/src/app/[locale]/_components/hero-section/server.tsx
Add a class for dark mode compatibility to the hero section image and disable the filter effect.
> Add dark mode support for hero section image

- next/src/app/[locale]/(common-layout)/user/[handle]/project/[id]/_components/project-detail.server.tsx
- next/src/app/[locale]/(common-layout)/user/[handle]/project/[id]/page.tsx
- next/src/app/[locale]/_components/project/project-list.server.tsx
Refactor class names for image elements and implement dynamic imports for floating controls and project like button components.
> Improve code formatting and enhance dynamic imports

- next/src/app/[locale]/(common-layout)/user/[handle]/page/[slug]/_components/share-dialog.tsx
- next/src/app/[locale]/(common-layout)/user/[handle]/page/[slug]/_lib/fetch-page-context.ts
- next/src/app/[locale]/(common-layout)/user/[handle]/page/[slug]/page.tsx
- next/src/app/[locale]/_components/display-mode-cycle.client.tsx
- next/src/app/[locale]/_components/display-mode-cycle.tsx
- next/src/app/[locale]/_components/floating-controls.client.tsx
- next/src/app/[locale]/_components/segment-and-translation-section/client.tsx
- next/src/app/[locale]/_lib/display-preference.ts
- next/src/app/_context/display-provider.tsx
- next/src/app/_context/display-types.ts
- next/src/app/api/og/route.tsx
Introduce new display mode types and remove the old display-preference logic. Enhance the DisplayModeCycle component with an afterClick property for better callback handling during mode switching. Update related component logic accordingly.
> Add display mode types and update related components

- next/src/app/[locale]/(common-layout)/page.tsx
Implement pagination for the PopularProjectList and NewProjectList components to enhance navigation and user experience.
> Add pagination to Popular and New Project Lists

- next/package.json
- next/src/app/[locale]/_lib/file-from-url.ts
- next/src/app/[locale]/_lib/html-to-mdast-with-segments.ts
- next/src/app/[locale]/_lib/remark-auto-upload-images.test.ts
- next/src/app/[locale]/_lib/remark-auto-upload-images.ts
Enhance the automatic image upload functionality by improving the file retrieval process and adding tests to ensure reliability.
> Improve automatic image upload feature and refactor file retrieval logic

- next/src/app/[locale]/_components/page/page-list.server.tsx
Adjust styles in the PageList component for better layout and eliminate the display of OGP images.
> Fix styles in PageList component and remove OGP image display

- README.md
- update repository clone URL
- update directories in install steps
- `bun run check` *(fails: bunx command not found)*
> Fix README clone path and directories

- next/prisma/seed.ts
Implement various code modifications to enhance functionality and performance.
> クリエイター向けに変更

- next/src/app/[locale]/(edit-layout)/user/[handle]/page/[pageSlug]/edit/_components/edit-page-client.tsx
- next/src/app/[locale]/(edit-layout)/user/[handle]/page/[pageSlug]/edit/_components/header/client.tsx
Modify the width of the PopoverContent in the EditHeader component and add a grow class to the main element in the EditPageClient component for improved styling.
> Adjust styles for EditHeader and EditPageClient components

- src/app/[locale]/(edit-layout)/user/[handle]/page/[pageSlug]/edit/_components/editor/editor-config.test.ts
- src/app/[locale]/(edit-layout)/user/[handle]/page/[pageSlug]/edit/_components/editor/editor-config.ts
Add functionality to normalize line breaks during HTML paste operations and enhance the consistency of the HTML transformation process through updated test expectations.
> Implement HTML transformation for pasted content and improve test cases
